#!/usr/bin/env python3
"""
Sparky Analysis with Ollama (local LLM, zero cost)

Requirements:
  - Ollama installed: curl -fsSL https://ollama.com/install.sh | sh
  - Model pulled: ollama pull llama3
"""

import json
import subprocess
import sys
from datetime import date
from pathlib import Path

def run_ollama(prompt, model="llama3"):
    """Run Ollama with a prompt and return the response."""
    result = subprocess.run(
        ["ollama", "run", model],
        input=prompt,
        capture_output=True,
        text=True,
        check=True
    )
    return result.stdout

def load_data(date_str):
    """Load collected data for a specific date."""
    data_dir = Path("data/raw")

    summary_file = data_dir / f"{date_str}-summary.json"
    commits_file = data_dir / f"{date_str}-commits.json"
    prs_file = data_dir / f"{date_str}-prs.json"

    if not summary_file.exists():
        print(f"❌ No data found for {date_str}")
        print(f"   Run: ./docs/examples/collect-gh.sh")
        sys.exit(1)

    with open(summary_file) as f:
        summary = json.load(f)

    with open(commits_file) as f:
        commits = json.load(f)

    with open(prs_file) as f:
        prs = json.load(f)

    return summary, commits, prs

def create_analysis_prompt(summary, commits, prs):
    """Create a prompt for Ollama to analyze the data."""

    # Sample some commits and PRs to keep prompt reasonable
    sample_commits = commits[:20] if len(commits) > 20 else commits
    sample_prs = prs[:10] if len(prs) > 10 else prs

    prompt = f"""You are a technical writer for raibid-labs, an open-source organization.
Analyze this development activity data and create a compelling daily digest.

## Summary Statistics
- Total commits: {summary['commits']}
- Pull requests merged: {summary['pull_requests']}
- Issues activity: {summary['issues']}
- Active repositories: {summary['active_repositories']}
- Active contributors: {summary['contributors']}

## Top Contributors
{json.dumps(summary['top_contributors'], indent=2)}

## Sample Commits
{json.dumps(sample_commits, indent=2)}

## Merged Pull Requests
{json.dumps(sample_prs, indent=2)}

## Your Task
Create a daily digest with these sections:

1. **Headline**: Catchy summary of the day
2. **Key Highlights**: 3-5 bullet points of notable activity
3. **Top Contributors**: Celebrate the most active developers
4. **Active Projects**: Mention repos with significant activity
5. **Notable Changes**: Interesting commits or PRs

Style:
- Casual but professional tone
- 200-300 words total
- Use emojis sparingly (🚀, 🔥, ✨)
- Celebrate accomplishments
- Be specific (mention names, repos, PRs by number)

Format: Markdown with clear headings
"""
    return prompt

def main():
    date_str = date.today().isoformat()

    print(f"🤖 Sparky Analysis with Ollama")
    print(f"📅 Date: {date_str}")
    print(f"🧠 Model: llama3 (local, free)")
    print()

    # Check if Ollama is installed
    try:
        subprocess.run(["ollama", "--version"], capture_output=True, check=True)
    except FileNotFoundError:
        print("❌ Ollama not found!")
        print("   Install: curl -fsSL https://ollama.com/install.sh | sh")
        print("   Then run: ollama pull llama3")
        sys.exit(1)

    # Load data
    print("📂 Loading data...")
    summary, commits, prs = load_data(date_str)
    print(f"   ✅ Loaded: {summary['commits']} commits, {summary['pull_requests']} PRs")

    # Create prompt
    print("📝 Creating analysis prompt...")
    prompt = create_analysis_prompt(summary, commits, prs)

    # Run Ollama
    print("🧠 Running Ollama (this may take 10-30 seconds)...")
    analysis = run_ollama(prompt)

    # Save output
    output_dir = Path("output/daily")
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / f"{date_str}.md"

    with open(output_file, "w") as f:
        f.write(f"# raibid-labs Daily Digest - {date_str}\n\n")
        f.write(analysis)
        f.write("\n\n---\n\n")
        f.write("*Generated by Sparky | Powered by Ollama (llama3) | Zero cost*\n")

    print()
    print(f"✅ Analysis complete!")
    print(f"   Saved to: {output_file}")
    print()
    print("Preview:")
    print("=" * 60)
    with open(output_file) as f:
        content = f.read()
        # Print first 40 lines
        lines = content.split('\n')
        for line in lines[:40]:
            print(line)
        if len(lines) > 40:
            print("...")
    print("=" * 60)
    print()
    print("💰 Cost: $0 (local Ollama)")

if __name__ == "__main__":
    main()
