#!/bin/bash
# Simple rule-based analysis (no AI, zero cost)

set -euo pipefail

DATE=$(date +%Y-%m-%d)
INPUT_DIR="data/raw"
OUTPUT_DIR="output/daily"
mkdir -p "$OUTPUT_DIR"

echo "🔍 Analyzing data for $DATE (rule-based, no AI)"

# Load summary
SUMMARY="$INPUT_DIR/$DATE-summary.json"
if [ ! -f "$SUMMARY" ]; then
  echo "❌ No data found for $DATE. Run collect-gh.sh first."
  exit 1
fi

# Extract stats
COMMITS=$(jq -r '.commits' "$SUMMARY")
PRS=$(jq -r '.pull_requests' "$SUMMARY")
ISSUES=$(jq -r '.issues' "$SUMMARY")
ACTIVE_REPOS=$(jq -r '.active_repositories' "$SUMMARY")
CONTRIBUTORS=$(jq -r '.contributors' "$SUMMARY")

# Top contributors
TOP_CONTRIBUTORS=$(jq -r '.top_contributors[] | "- **\(.name)**: \(.commits) commits"' "$SUMMARY")

# Active repos list
REPOS_LIST=$(jq -r '.active_repos[] | "- \(.)"' "$SUMMARY")

# Notable commits (first 10)
NOTABLE_COMMITS=$(jq -r '.[] | "- **[\(.repo)]** \(.message) (@\(.author))"' "$INPUT_DIR/$DATE-commits.json" | head -10)

# Merged PRs
MERGED_PRS=$(jq -r '.[] | "- **[\(.repo)]** #\(.number): \(.title) (@\(.author.login))"' "$INPUT_DIR/$DATE-prs.json")

# Determine activity level
if [ "$COMMITS" -gt 50 ]; then
  ACTIVITY_EMOJI="🔥"
  ACTIVITY_LEVEL="Very High"
elif [ "$COMMITS" -gt 20 ]; then
  ACTIVITY_EMOJI="🚀"
  ACTIVITY_LEVEL="High"
elif [ "$COMMITS" -gt 10 ]; then
  ACTIVITY_EMOJI="⚡"
  ACTIVITY_LEVEL="Moderate"
else
  ACTIVITY_EMOJI="📊"
  ACTIVITY_LEVEL="Light"
fi

# Generate daily digest
cat > "$OUTPUT_DIR/$DATE.md" <<EOF
# raibid-labs Daily Digest - $DATE

$ACTIVITY_EMOJI **Activity Level:** $ACTIVITY_LEVEL

## Overview

Today's development activity across the raibid-labs organization:

- **$COMMITS commits** across $ACTIVE_REPOS repositories
- **$PRS pull requests** merged
- **$ISSUES issues** created or updated
- **$CONTRIBUTORS active contributors**

## 🏆 Top Contributors

$TOP_CONTRIBUTORS

## 🚀 Active Projects

$REPOS_LIST

## 📝 Notable Commits

$NOTABLE_COMMITS

$(if [ "$PRS" -gt 0 ]; then
  echo "## 🔀 Merged Pull Requests"
  echo ""
  echo "$MERGED_PRS"
fi)

---

*Generated by Sparky | Rule-based analysis | Zero cost*
*Raw data: \`$INPUT_DIR/$DATE-*.json\`*
EOF

echo ""
echo "✅ Analysis complete!"
echo ""
echo "Generated: $OUTPUT_DIR/$DATE.md"
echo ""
echo "Preview:"
echo "----------------------------------------"
head -20 "$OUTPUT_DIR/$DATE.md"
echo "..."
echo "----------------------------------------"
echo ""
echo "💰 Cost: $0 (pure bash + jq)"
