#!/usr/bin/env nu
# Sparky Weekly Analysis (Nushell + Ollama)
# Zero cost - local LLM

def main [] {
    let week = (date now | format date "%Y-W%V")
    let date = (date now | format date "%Y-%m-%d")
    let data_dir = "data/raw"
    let output_dir = "output/weekly"

    print "🤖 Sparky Weekly Analysis with Ollama"
    print $"📅 Week: ($week)"
    print "🧠 Model: llama3.2 (local, free, better for prose)"
    print ""

    # Check if ollama is installed
    if (which ollama | is-empty) {
        print "❌ Ollama not found!"
        print ""
        print "Install Ollama with:"
        print "  just install-ollama"
        print ""
        print "Or manually:"
        print "  curl -fsSL https://ollama.com/install.sh | sh"
        print "  ollama pull llama3.2"
        exit 1
    }

    # Check if data exists
    let summary_file = $"($data_dir)/($week)-summary.json"
    if not ($summary_file | path exists) {
        print $"❌ No data found for ($week)"
        print "   Run: nu scripts/collect-weekly.nu"
        exit 1
    }

    # Load data
    print "📂 Loading weekly data..."
    let summary = (open $summary_file)
    let commits = (open $"($data_dir)/($week)-commits.json")
    let prs = (open $"($data_dir)/($week)-prs.json")
    let issues = (open $"($data_dir)/($week)-issues.json")

    print $"   ✅ Loaded: ($summary.commits) commits, ($summary.pull_requests) PRs, ($summary.issues) issues"

    # Sample data to keep prompt reasonable
    let sample_commits = ($commits | first 50)
    let sample_prs = ($prs | first 20)
    let sample_issues = ($issues | first 15)

    # Create analysis prompt
    print "📝 Creating weekly analysis prompt..."

    # Format data as readable text
    let top_contributors_text = ($summary.top_contributors
        | each {|c| $"- ($c.name): ($c.commits) commits"}
        | str join "\n")

    let active_repos_text = ($summary.active_repos
        | each {|r| $"- ($r)"}
        | str join "\n")

    let sample_commits_text = ($sample_commits
        | each {|c| $"[($c.repo)] ($c.message | lines | first)"}
        | str join "\n")

    let prompt = $"Write a weekly development report for raibid-labs open-source organization.

ACTUAL DATA FROM WEEK ($summary.week):

Commits: ($summary.commits)
Pull Requests: ($summary.pull_requests)
Issues: ($summary.issues)
Active Repos: ($summary.active_repositories)
Contributors: ($summary.contributors)

TOP CONTRIBUTORS:
($top_contributors_text)

ACTIVE REPOSITORIES:
($active_repos_text)

RECENT COMMITS:
($sample_commits_text)

Write a 500-800 word report with:
1. Overview - what happened this week
2. Top contributors and their impact
3. Most active repositories
4. Notable commits or changes

Use ONLY the data above. Be specific with names and numbers. Professional tone."

    # Run Ollama (use llama3.2 for better prose, or qwen2.5-coder for code-focused)
    print "🧠 Running Ollama (this may take 30-60 seconds for weekly report)..."

    # Try llama3.2 first (better for prose), fallback to qwen2.5-coder
    let model = "llama3.2"
    let analysis_raw = (echo $prompt | ollama run $model)

    # Post-process: Convert repository references to proper markdown links
    print "🔗 Adding repository links..."
    mut analysis = $analysis_raw
    for repo in $summary.active_repos {
        # Replace [repo-name] with [repo-name](https://github.com/raibid-labs/repo-name)
        # But only if not already a link (not followed by parenthesis)
        let pattern = $'\[($repo)\](?!\()'
        let url = $'https://github.com/raibid-labs/($repo)'
        let replacement = $'[($repo)]' + '(' + $url + ')'
        $analysis = ($analysis | str replace --all --regex $pattern $replacement)
    }

    # Create output directory
    mkdir $output_dir

    # Generate report
    let output_file = $"($output_dir)/($week).md"

    let report = $"# This Week in raibid-labs - ($week)

*Week ending ($date)*

---

($analysis)

---

*Generated by Sparky | Powered by Ollama \(llama3.2) | Zero cost*
"

    $report | save -f $output_file

    print ""
    print "✅ Weekly analysis complete!"
    print $"   Saved to: ($output_file)"
    print ""
    print "Preview:"
    print "=" * 80
    let lines = ($report | lines)
    let preview_lines = if ($lines | length) > 50 { 50 } else { ($lines | length) }
    $lines | first $preview_lines | each {|line| print $line}
    if ($lines | length) > 50 {
        print "..."
        print $"[($lines | length | $in - 50) more lines]"
    }
    print "=" * 80
    print ""
    print "💰 Cost: $0 (local Ollama)"
    print ""
    print "📊 Statistics:"
    print $"   - ($summary.commits) commits across ($summary.active_repositories) repositories"
    print $"   - ($summary.contributors) active contributors"
    print $"   - ($summary.pull_requests) PRs merged"
}
