#!/usr/bin/env nu
# Sparky Weekly Analysis (Nushell + Ollama)
# Zero cost - local LLM

def main [] {
    let week = (date now | format date "%Y-W%V")
    let date = (date now | format date "%Y-%m-%d")
    let data_dir = "data/raw"
    let output_dir = "output/weekly"

    print "🤖 Sparky Weekly Analysis with Ollama"
    print $"📅 Week: ($week)"
    print "🧠 Model: qwen2.5-coder:1.5b (local, free, code-specialized)"
    print ""

    # Check if ollama is installed
    if (which ollama | is-empty) {
        print "❌ Ollama not found!"
        print ""
        print "Install Ollama with:"
        print "  just install-ollama"
        print ""
        print "Or manually:"
        print "  curl -fsSL https://ollama.com/install.sh | sh"
        print "  ollama pull qwen2.5-coder:1.5b"
        exit 1
    }

    # Check if data exists
    let summary_file = $"($data_dir)/($week)-summary.json"
    if not ($summary_file | path exists) {
        print $"❌ No data found for ($week)"
        print "   Run: nu scripts/collect-weekly.nu"
        exit 1
    }

    # Load data
    print "📂 Loading weekly data..."
    let summary = (open $summary_file)
    let commits = (open $"($data_dir)/($week)-commits.json")
    let prs = (open $"($data_dir)/($week)-prs.json")
    let issues = (open $"($data_dir)/($week)-issues.json")

    print $"   ✅ Loaded: ($summary.commits) commits, ($summary.pull_requests) PRs, ($summary.issues) issues"

    # Sample data to keep prompt reasonable
    let sample_commits = ($commits | first 50)
    let sample_prs = ($prs | first 20)
    let sample_issues = ($issues | first 15)

    # Create analysis prompt
    print "📝 Creating weekly analysis prompt..."

    let prompt = $"You are a technical writer for raibid-labs, an open-source organization.
Analyze this week's development activity and create a compelling weekly report.

## Summary Statistics
- Week: ($summary.week)
- Total commits: ($summary.commits)
- Pull requests merged: ($summary.pull_requests)
- Issues activity: ($summary.issues)
- Active repositories: ($summary.active_repositories)
- Active contributors: ($summary.contributors)

## Daily Commit Activity
($summary.commits_per_day | to json)

## Top Contributors
($summary.top_contributors | to json)

## Active Repositories
($summary.active_repos | to json)

## Sample Commits
($sample_commits | to json)

## Merged Pull Requests
($sample_prs | to json)

## Issue Activity
($sample_issues | to json)

## Your Task
Create a comprehensive weekly report with these sections:

1. **Weekly Overview**: 2-3 sentence summary of the week's theme/highlights
2. **Key Achievements**: 5-7 bullet points of major accomplishments
3. **Repository Spotlight**: Highlight 2-3 repos with significant activity
4. **Notable Contributions**: Call out specific PRs, commits, or issues that stand out
5. **Contributor Highlights**: Celebrate the most active contributors with specific examples
6. **Trends & Patterns**: Any interesting patterns in the data \(spike in commits, new contributors, etc.)
7. **Looking Ahead**: Brief mention of ongoing work or upcoming releases

Style Guidelines:
- Professional but approachable tone
- 800-1200 words total
- Use emojis sparingly for visual interest \(🚀, 🔥, ✨, 📊, 🎯)
- Be specific: mention repo names, PR numbers, contributor names
- Celebrate accomplishments and team collaboration
- Include data/metrics to back up observations
- Tell a cohesive story about the week

Format: Markdown with clear headings and subheadings"

    # Run Ollama
    print "🧠 Running Ollama (this may take 30-60 seconds for weekly report)..."

    let analysis = (echo $prompt | ollama run qwen2.5-coder:1.5b)

    # Create output directory
    mkdir $output_dir

    # Generate report
    let output_file = $"($output_dir)/($week).md"

    let report = $"# This Week in raibid-labs - ($week)

*Week ending ($date)*

---

($analysis)

---

*Generated by Sparky | Powered by Ollama \(qwen2.5-coder:1.5b) | Zero cost*
"

    $report | save -f $output_file

    print ""
    print "✅ Weekly analysis complete!"
    print $"   Saved to: ($output_file)"
    print ""
    print "Preview:"
    print "=" * 80
    let lines = ($report | lines)
    let preview_lines = if ($lines | length) > 50 { 50 } else { ($lines | length) }
    $lines | first $preview_lines | each {|line| print $line}
    if ($lines | length) > 50 {
        print "..."
        print $"[($lines | length | $in - 50) more lines]"
    }
    print "=" * 80
    print ""
    print "💰 Cost: $0 (local Ollama)"
    print ""
    print "📊 Statistics:"
    print $"   - ($summary.commits) commits across ($summary.active_repositories) repositories"
    print $"   - ($summary.contributors) active contributors"
    print $"   - ($summary.pull_requests) PRs merged"
}
