#!/usr/bin/env nu
# Sparky Daily Analysis (Nushell + Ollama)
# Zero cost - local LLM

def main [] {
    let date = (date now | format date "%Y-%m-%d")
    let data_dir = "data/raw"
    let output_dir = "output/daily"

    print "🤖 Sparky Daily Analysis with Ollama"
    print $"📅 Date: ($date)"
    print "🧠 Model: llama3.2 (local, free, better for prose)"
    print ""

    # Check if ollama is installed
    if (which ollama | is-empty) {
        print "❌ Ollama not found!"
        print ""
        print "Install Ollama with:"
        print "  just install-ollama"
        print ""
        print "Or manually:"
        print "  curl -fsSL https://ollama.com/install.sh | sh"
        print "  ollama pull llama3.2"
        exit 1
    }

    # Check if data exists
    let summary_file = $"($data_dir)/($date)-summary.json"
    if not ($summary_file | path exists) {
        print $"❌ No data found for ($date)"
        print "   Run: nu scripts/collect-daily.nu"
        exit 1
    }

    # Load data
    print "📂 Loading data..."
    let summary = (open $summary_file)
    let commits = (open $"($data_dir)/($date)-commits.json")
    let prs = (open $"($data_dir)/($date)-prs.json")

    print $"   ✅ Loaded: ($summary.commits) commits, ($summary.pull_requests) PRs"

    # Sample data to keep prompt reasonable
    let sample_commits = ($commits | first 20)
    let sample_prs = ($prs | first 10)

    # Create analysis prompt
    print "📝 Creating analysis prompt..."

    # Format data as readable text
    let top_contributors_text = ($summary.top_contributors
        | each {|c| $"- ($c.name): ($c.commits) commits"}
        | str join "\n")

    let sample_commits_text = ($sample_commits
        | each {|c| $"[($c.repo)] ($c.message | lines | first)"}
        | str join "\n")

    let prompt = $"Write a daily development summary for raibid-labs open-source organization.

ACTUAL DATA FROM ($summary.date):

Commits: ($summary.commits)
Pull Requests: ($summary.pull_requests)
Issues: ($summary.issues)
Active Repos: ($summary.active_repositories)
Contributors: ($summary.contributors)

TOP CONTRIBUTORS:
($top_contributors_text)

RECENT COMMITS:
($sample_commits_text)

Write a 200-300 word summary with:
1. What happened today
2. Top contributors
3. Notable changes

Use ONLY the data above. Be specific with names. Professional but casual tone."

    # Run Ollama
    print "🧠 Running Ollama (this may take 10-30 seconds)..."

    let analysis = (echo $prompt | ollama run llama3.2)

    # Create output directory
    mkdir $output_dir

    # Generate report
    let output_file = $"($output_dir)/($date).md"

    let report = $"# raibid-labs Daily Digest - ($date)

($analysis)

---

*Generated by Sparky | Powered by Ollama \(llama3.2) | Zero cost*
"

    $report | save -f $output_file

    print ""
    print "✅ Analysis complete!"
    print $"   Saved to: ($output_file)"
    print ""
    print "Preview:"
    print "=" * 60
    let lines = ($report | lines)
    let preview_lines = if ($lines | length) > 40 { 40 } else { ($lines | length) }
    $lines | first $preview_lines | each {|line| print $line}
    if ($lines | length) > 40 {
        print "..."
    }
    print "=" * 60
    print ""
    print "💰 Cost: $0 (local Ollama)"
}
