#!/usr/bin/env nu
# Sparky Daily Analysis (Nushell + Ollama)
# Zero cost - local LLM

def main [] {
    let date = (date now | format date "%Y-%m-%d")
    let data_dir = "data/raw"
    let output_dir = "output/daily"

    print "🤖 Sparky Daily Analysis with Ollama"
    print $"📅 Date: ($date)"
    print "🧠 Model: qwen2.5-coder:1.5b (local, free, code-specialized)"
    print ""

    # Check if ollama is installed
    if (which ollama | is-empty) {
        print "❌ Ollama not found!"
        print ""
        print "Install Ollama with:"
        print "  just install-ollama"
        print ""
        print "Or manually:"
        print "  curl -fsSL https://ollama.com/install.sh | sh"
        print "  ollama pull qwen2.5-coder:1.5b"
        exit 1
    }

    # Check if data exists
    let summary_file = $"($data_dir)/($date)-summary.json"
    if not ($summary_file | path exists) {
        print $"❌ No data found for ($date)"
        print "   Run: nu scripts/collect-daily.nu"
        exit 1
    }

    # Load data
    print "📂 Loading data..."
    let summary = (open $summary_file)
    let commits = (open $"($data_dir)/($date)-commits.json")
    let prs = (open $"($data_dir)/($date)-prs.json")

    print $"   ✅ Loaded: ($summary.commits) commits, ($summary.pull_requests) PRs"

    # Sample data to keep prompt reasonable
    let sample_commits = ($commits | first 20)
    let sample_prs = ($prs | first 10)

    # Create analysis prompt
    print "📝 Creating analysis prompt..."

    let prompt = $"You are a technical writer for raibid-labs, an open-source organization.
Analyze this development activity data and create a compelling daily digest.

## Summary Statistics
- Total commits: ($summary.commits)
- Pull requests merged: ($summary.pull_requests)
- Issues activity: ($summary.issues)
- Active repositories: ($summary.active_repositories)
- Active contributors: ($summary.contributors)

## Top Contributors
($summary.top_contributors | to json)

## Sample Commits
($sample_commits | to json)

## Merged Pull Requests
($sample_prs | to json)

## Your Task
Create a daily digest with these sections:

1. **Headline**: Catchy summary of the day
2. **Key Highlights**: 3-5 bullet points of notable activity
3. **Top Contributors**: Celebrate the most active developers
4. **Active Projects**: Mention repos with significant activity
5. **Notable Changes**: Interesting commits or PRs

Style:
- Casual but professional tone
- 200-300 words total
- Use emojis sparingly \(🚀, 🔥, ✨)
- Celebrate accomplishments
- Be specific \(mention names, repos, PRs by number)

Format: Markdown with clear headings"

    # Run Ollama
    print "🧠 Running Ollama (this may take 10-30 seconds)..."

    let analysis = (echo $prompt | ollama run qwen2.5-coder:1.5b)

    # Create output directory
    mkdir $output_dir

    # Generate report
    let output_file = $"($output_dir)/($date).md"

    let report = $"# raibid-labs Daily Digest - ($date)

($analysis)

---

*Generated by Sparky | Powered by Ollama \(qwen2.5-coder:1.5b) | Zero cost*
"

    $report | save -f $output_file

    print ""
    print "✅ Analysis complete!"
    print $"   Saved to: ($output_file)"
    print ""
    print "Preview:"
    print "=" * 60
    let lines = ($report | lines)
    let preview_lines = if ($lines | length) > 40 { 40 } else { ($lines | length) }
    $lines | first $preview_lines | each {|line| print $line}
    if ($lines | length) > 40 {
        print "..."
    }
    print "=" * 60
    print ""
    print "💰 Cost: $0 (local Ollama)"
}
