#!/usr/bin/env nu
# Sparky Publishing Script (Nushell)
# Publishes generated reports to raibid-labs/docs blog

def main [
    mode: string = "weekly"  # daily, weekly, monthly, or all
    --dry-run               # Show what would be published without actually publishing
] {
    let docs_repo = "raibid-labs/docs"
    let docs_dir = ".sparky-docs-temp"

    print "📝 Sparky Publishing"
    print $"Mode: ($mode)"
    if $dry_run {
        print "🔍 DRY RUN - No actual changes will be made"
    }
    print ""

    # Clone or update docs repo
    print "📦 Preparing docs repository..."
    if ($docs_dir | path exists) {
        print "   Pulling latest changes..."
        cd $docs_dir
        git pull
        cd ..
    } else {
        print "   Cloning docs repository..."
        gh repo clone $docs_repo $docs_dir
    }

    # Create blog directory structure
    let blog_dir = $"($docs_dir)/content/blog"
    mkdir $blog_dir

    # Create blog index if it doesn't exist
    let blog_index = $"($blog_dir)/index.md"
    if not ($blog_index | path exists) {
        create_blog_index $blog_index
    }

    # Publish based on mode
    match $mode {
        "daily" => { publish_daily $blog_dir $dry_run }
        "weekly" => { publish_weekly $blog_dir $dry_run }
        "monthly" => { publish_monthly $blog_dir $dry_run }
        "all" => {
            publish_daily $blog_dir $dry_run
            publish_weekly $blog_dir $dry_run
            publish_monthly $blog_dir $dry_run
        }
        _ => {
            print $"❌ Invalid mode: ($mode)"
            print "   Valid modes: daily, weekly, monthly, all"
            exit 1
        }
    }

    # Commit and push if not dry run
    if not $dry_run {
        print ""
        print "📤 Publishing to GitHub..."
        cd $docs_dir
        git add content/blog/

        let changes = (git status --porcelain | lines | where {|line| $line starts-with " M" or $line starts-with "A " or $line starts-with "??"})

        if ($changes | length) > 0 {
            git commit -m $"Add Sparky ($mode) report - (date now | format date '%Y-%m-%d')

Generated by Sparky automation

🤖 Generated with Sparky
"
            git push
            print "✅ Published successfully!"
        } else {
            print "ℹ️  No new reports to publish"
        }
        cd ..
    } else {
        print ""
        print "🔍 DRY RUN complete - no changes made"
    }

    print ""
    print "💰 Cost: $0 (GitHub Pages is free!)"
}

def create_blog_index [index_path: string] {
    let content = "---
title: Sparky Development Blog
description: Automated development reports from raibid-labs
tags: [blog, sparky, reports]
---

# Sparky Development Blog

Automated development activity reports for raibid-labs, generated by Sparky.

## 📊 Report Types

- **Daily Digests** - Quick summaries of daily activity
- **Weekly Reports** - Comprehensive weekly overviews
- **Monthly Reviews** - In-depth monthly analysis

## 🗂️ Browse Reports

- [[content/blog/2025/index|2025 Reports]]

## 🤖 About Sparky

Sparky is raibid-labs' AI-powered development activity monitor. It automatically:
- Monitors git activity across all repositories
- Generates intelligent summaries using local LLM
- Publishes reports to this blog

**Zero cost. 100% open source. Fully automated.**

---

*Powered by [Sparky](https://github.com/raibid-labs/sparky) | Generated with Ollama (llama3.2)*
"
    $content | save $index_path
    print $"   Created blog index: ($index_path)"
}

def publish_daily [blog_dir: string, dry_run: bool] {
    let date = (date now | format date "%Y-%m-%d")
    let year = (date now | format date "%Y")
    let month = (date now | format date "%m")

    let source = $"output/daily/($date).md"

    if not ($source | path exists) {
        print $"⚠️  No daily report found for ($date)"
        print $"   Run: just demo-daily"
        return
    }

    let year_dir = $"($blog_dir)/($year)"
    let month_dir = $"($year_dir)/($month)"
    mkdir $month_dir

    let dest = $"($month_dir)/($date).md"

    # Read source and add frontmatter
    let content = (open $source)
    let title = $"Daily Digest - ($date)"

    let with_frontmatter = $"---
title: \"($title)\"
description: \"Development activity summary for raibid-labs\"
date: ($date)
tags: [sparky, daily-digest, development]
author: Sparky
---

($content)"

    if $dry_run {
        print $"📄 Would publish: ($dest)"
    } else {
        $with_frontmatter | save -f $dest
        print $"✅ Published daily: ($dest)"
    }
}

def publish_weekly [blog_dir: string, dry_run: bool] {
    let week = (date now | format date "%Y-W%V")
    let year = (date now | format date "%Y")
    let month = (date now | format date "%m")
    let date = (date now | format date "%Y-%m-%d")

    let source = $"output/weekly/($week).md"

    if not ($source | path exists) {
        print $"⚠️  No weekly report found for ($week)"
        print $"   Run: just demo-weekly"
        return
    }

    let year_dir = $"($blog_dir)/($year)"
    let month_dir = $"($year_dir)/($month)"
    mkdir $month_dir

    let dest = $"($month_dir)/week-($week | str replace 'W' '').md"

    # Read source and add frontmatter
    let content = (open $source)
    let title = $"This Week in raibid-labs - ($week)"

    let with_frontmatter = $"---
title: \"($title)\"
description: \"Weekly development report for raibid-labs\"
date: ($date)
tags: [sparky, weekly-report, development]
author: Sparky
---

($content)"

    if $dry_run {
        print $"📄 Would publish: ($dest)"
    } else {
        $with_frontmatter | save -f $dest
        print $"✅ Published weekly: ($dest)"
    }
}

def publish_monthly [blog_dir: string, dry_run: bool] {
    let month = (date now | format date "%Y-%m")
    let year = (date now | format date "%Y")
    let month_num = (date now | format date "%m")
    let month_name = (date now | format date "%B %Y")
    let date = (date now | format date "%Y-%m-%d")

    let source = $"output/monthly/($month).md"

    if not ($source | path exists) {
        print $"⚠️  No monthly report found for ($month)"
        print $"   Run: just demo-monthly"
        return
    }

    let year_dir = $"($blog_dir)/($year)"
    let month_dir = $"($year_dir)/($month_num)"
    mkdir $month_dir

    let dest = $"($month_dir)/($month_name | str replace ' ' '-' | str downcase).md"

    # Read source and add frontmatter
    let content = (open $source)
    let title = $"raibid-labs Monthly Review - ($month_name)"

    let with_frontmatter = $"---
title: \"($title)\"
description: \"Comprehensive monthly development review for raibid-labs\"
date: ($date)
tags: [sparky, monthly-review, development]
author: Sparky
---

($content)"

    if $dry_run {
        print $"📄 Would publish: ($dest)"
    } else {
        $with_frontmatter | save -f $dest
        print $"✅ Published monthly: ($dest)"
    }
}
